Repository JuliaLang/LinearAlgebra.jl, pull requests merged in 2024-12, with the labels that each got.

#1108 Non-contiguous matrices in triangular mul! and div!
  src/triangular.jl
  test/triangular.jl
Labels: backport 1.11, backport 1.10

#1132 Cache and reuse `R` in adjoint `QR` `ldiv!`
  src/qr.jl
Labels: performance

#1141 don't refer to internal variable names in gemv exceptions
  src/matmul.jl
Labels: docs

#1137 bring back [l/r]mul! shortcuts for (kn)own triangular types
  src/triangular.jl
Labels: backport 1.11

#1135 Higher-order functions in `factorize` to obtain structure
  src/dense.jl
  test/dense.jl
Labels: performance

#1156 `sqrt`, `cbrt` and `log` for dense diagonal matrices
  src/dense.jl
  test/dense.jl
Labels: arrays, performance
