Repository JuliaLang/LinearAlgebra.jl, pull requests merged in 2025-02, with the labels that each got.

#1186 remove copy-allocation on accessing `cholesky` factors (`.L`, `.U`)
  src/cholesky.jl
  test/cholesky.jl
Labels: performance

#1202 Add fast path in generic matmul
  src/matmul.jl
  test/matmul.jl
Labels: performance, backport 1.12

#1203 Restrict Diagonal sqrt branch to positive diag
  src/dense.jl
  test/dense.jl
Labels: backport 1.12

#1211 Loop over `diagind` in `diag` for banded matrices
  src/bidiag.jl
  src/diagonal.jl
  src/tridiag.jl
Labels: arrays, performance

#1206 Don't mutate arrays in symmetric trig functions
  src/symmetric.jl
Labels: arrays

#1210 Indirection in matrix multiplication to avoid ambiguities
  src/diagonal.jl
  src/matmul.jl
Labels: backport 1.12

#1207 Specialize Diagonal * Adjoint
  src/adjtrans.jl
  src/diagonal.jl
Labels: backport 1.11, backport 1.12

#1223 Add `getindex` for `SymTridiagonal` using a `BandIndex`
  src/tridiag.jl
Labels: performance

#1229 Forward `Diagonal` `rmul!`/`lmul!` for adj/trans to parent
  src/diagonal.jl
  test/diagonal.jl
Labels: performance

#1228 Specialize `lmul!`/`rmul!` for strided triangular matrices
  src/diagonal.jl
  test/diagonal.jl
Labels: performance

#1224 Out-of-place copytri in dense trig functions
  src/dense.jl
  test/dense.jl
Labels: enhancement, arrays

#1230 Avoid materializing `diag` in `Diagonal` `kron`
  src/diagonal.jl
Labels: performance

#1212 `convert` to banded matrix types from `AbstractMatrix`es
  src/bidiag.jl
  src/tridiag.jl
  test/bidiag.jl
  test/special.jl
  test/tridiag.jl
Labels: enhancement, arrays

#1218 Support indexing `Tridiagonal`/`SymTridiagonal` block matrices
  src/tridiag.jl
  test/bidiag.jl
  test/tridiag.jl
Labels: arrays
