Repository JuliaLang/LinearAlgebra.jl, pull requests merged in 2025-06, with the labels that each got.

#1363 Change default symmetriceigen algorithm back to RobustRepresentations
  src/symmetriceigen.jl
Labels: backport 1.12

#1365 Add docstring to the `rank(::QRPivoted)` method
  src/qr.jl
Labels: backport 1.12

#1395 lu!(F, ::Matrix) requires Julia 1.13
  src/lu.jl
Labels: docs

#1387 stable pinv least-squares via rtol,atol in svd, ldiv!
  src/dense.jl
  src/svd.jl
  test/svd.jl
Labels: enhancement
