Repository JuliaLang/LinearAlgebra.jl, pull requests merged in 2025-08, with the labels that each got.

#1396 Add 5-arg symmetric-adjoint multiplication tests
  test/symmetric.jl
  test/testhelpers/Quaternions.jl
Labels: test

#1418 Fix overflow and type issues with generic det of a triangular matrix
  src/generic.jl
  test/generic.jl
Labels: backport 1.11, backport 1.10, backport 1.12

#1419 Improve type-stability of `eigencopy_oftype`
  src/symmetriceigen.jl
Labels: backport 1.12

#1305 Bounds-checking in triangular indexing branches
  src/triangular.jl
  test/triangular.jl
Labels: backport 1.11, backport 1.10, backport 1.12

#1388 Specialize lmul!/rmul! for adjoint/transpose
  src/adjtrans.jl
  test/adjtrans.jl
Labels: forget me not

#1410 Generalize 3-arg `dot` to `HermOrSym`
  src/symmetric.jl
  test/symmetric.jl
Labels: performance
