Repository JuliaLang/LinearAlgebra.jl, pull requests merged in 2025-03, with the labels that each got.

#1214 Move `alg` to a keyword argument in symmetric eigen
  src/symmetriceigen.jl
  test/symmetric.jl
  test/symmetriceigen.jl
Labels: backport 1.12

#1215 Make use of `mul` indirection
  src/bidiag.jl
  src/diagonal.jl
  src/hessenberg.jl
  src/special.jl
  src/symmetric.jl
  src/triangular.jl
  test/triangular.jl
Labels: backport 1.11, backport 1.10, backport 1.12

#1238 Ensure positive-definite matrix in lapack posv test
  test/lapack.jl
Labels: test
